name: Run Cypress Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Fail if test contains "it.only" or "describe.only"
        run: |
          if grep -r --include=\*.{js,ts} -E '\b(it|describe)\.only' cypress/e2e; then
            echo "🚫 Found .only in tests. Please remove it before merging."
            exit 1
          fi


      - name: Run Cypress tests headlessly
        run: npx cypress run
